### ISSUE TITLE
Please make a README

### ISSUE THREAD

**Issue by nqthqn** [daved/conch0#1]
What does it doooo?

**Comment by daved** [comment]
Soon.

**Comment by nqthqn** [comment]
💃 🍬 🎉 🎈 🎶  💯  👍 💃 🍬 🍰 💃 🍬 🎉 🎈 🎶  💯  👍 💃 🍬 🍰 💃 🍬 🎉 🎈 🎶  💯  👍 💃 🍬 🍰 💃 🍬 🎉 🎈 🎶  💯  👍 💃 🍬 🍰 💃 🍬 🎉 🎈 🎶  💯  👍 💃 🍬 🍰 💃 🍬 🎉 🎈 🎶  💯  👍 💃 🍬 🍰 💃 🍬 🎉 🎈 🎶  💯  👍 💃 🍬 🍰 💃 🍬 🎉 🎈 🎶  💯  👍 💃 🍬 🍰 💃 🍬 🎉 🎈 🎶  💯  👍 💃 🍬 🍰 💃 🍬 🎉 🎈 🎶  💯  👍 💃 🍬 🍰 💃 🍬 🎉 🎈 🎶  💯  👍 💃 🍬 🍰 💃 🍬 🎉 🎈 🎶  💯  👍 💃 🍬 🍰 💃 🍬 🎉 🎈 🎶  💯  👍 💃 🍬 🍰 💃 🍬 🎉 🎈 🎶  💯  👍 💃 🍬 🍰
