### ISSUE TITLE
When breaking on 4 core Linux, the app should consistently cancel and terminate

### ISSUE THREAD

**Issue by jazeee** [daved/conch0#2]
I enjoyed your presentation last week. I did run into one issue though.
When I was playing with conch0, I had some problems when breaking.
Intermittently, when I `Ctrl+c`, the app would hang, and not display canceled. I then click `Ctrl+c` again, which then threw an error about closing the already closed channel (`c.doneChan()`).

I am not 100% sure if this will reproduce the issue but this is what I did:
First, create 10,000 tiny gz files:
```
for i in `seq 1 10000`; do echo "test" | gzip -c > testfiles/a$i.gz ; done
```
Then run the app and quickly hit `Ctrl+c`. About half of the time, the app will cancel and terminate successfully, however, intermittently, the app halts and hangs.

I was able to fix it, but since I am new to go, I am unsure if I went the right path. See https://github.com/jazeee/conch0
I'll create a PR for this, and would appreciate any feedback or learning tips.
Thanks much!

**Comment by daved** [comment]
This does seem to be a bug.  Thanks for catching it.

The PR that you've since provided will require some discussion, and we'll take care of that in the PR comments.  Once we've settled that, you or I can fix this issue.

To note: For testing, you can also generate test files using `conchtestdata -qty=20000`.

**Comment by jazeee** [comment]
I can really cause a number of problems by running this:

```
while true; do 
  for j in `seq 1 5`; do 
    killall conch0-broken 2>/dev/null & 
    killall conch0-fixed 2>/dev/null & 
  done; 
  sleep 0.1s; 
done
```

(Note that I am renaming the executables to make it easier to compare)

While running `conch0-fixed -width 9000`

In the current code, this generally fails. In PR #5 this seems to be a fair bit more robust, in PR #3 it doesn't seem to work very well either...

**Comment by daved** [comment]
In order to have the signal monitor ignore all subsequent signals, the user must call `SignalMonitor.Stop()`.  I've corrected this in the master branch.
